# Generated by Django 3.0.6 on 2020-06-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_auto_20200602_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
    ]
