# Generated by Django 3.0.6 on 2020-06-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_auto_20200603_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Test Description'),
        ),
    ]
