# Generated by Django 3.0.6 on 2020-06-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0018_auto_20200606_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=213213231312, max_length=50),
            preserve_default=False,
        ),
    ]
